{% set name = "rhessysec" %}
{% set version = "7.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/DavidChoi76/rhessysec/archive/v{{ version }}.tar.gz

build:
  number: 0
  skip: true  # [win]

requirements:
  build: 
    - {{ compiler('c') }}
  host:
    - liblapack
    - libblas
  run:

test:
  commands:
    - rhessysecv{{ version }} -version 

about:
  home: https://github.com/DavidChoi76/rhessysec
  license:  GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: "Hydrologic modeling framework"

  description: |
    RHESSys is a GIS-based, hydro-ecological modeling framework designed 
    to simulate carbon, water, and nutrient fluxes. By combining a set of 
    physically-based process models and a methodology for partitioning and 
    parameterizing the landscape, RHESSys is capable of modeling the spatial 
    distribution and spatio-temporal interactions between different processes 
    at the watershed scale.
  doc_url: https://github.com/DavidChoi76/pyrhessys
  dev_url: https://github.com/DavidChoi76/rhessysec

extra:
  recipe-maintainers:
    - laurencelin
    - lband
    - DavidChoi76
