{% set version = "7.2" %}

package:
  name: rhessysEC
  version: {{ version }}

source:
  git_url: https://github.com/laurencelin/RHESSysEastCoast.git
  git_rev: v{{ version }}
  git_depth: -1 # (Defaults to -1/not shallow)

build:
  number: 0
  skip: true  # [win]

about:
  home: https://github.com/laurencelin/RHESSysEastCoast.git
  license:  GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: "Hydrologic modeling framework"

  description: |
    RHESSys is a GIS-based, hydro-ecological modeling framework designed 
    to simulate carbon, water, and nutrient fluxes. By combining a set of 
    physically-based process models and a methodology for partitioning and 
    parameterizing the landscape, RHESSys is capable of modeling the spatial 
    distribution and spatio-temporal interactions between different processes 
    at the watershed scale.
  doc_url: https://github.com/DavidChoi76/pyrhessys
  dev_url: https://github.com/laurencelin/RHESSysEastCoast.git

extra:
  recipe-maintainers:
    - laurencelin
    - lband
